import unittest
from pathlib import Path


class ReadmeTests(unittest.TestCase):
    def test_24h_loop_example_writes_auditable_log_and_exit_files(self) -> None:
        readme = Path("README.md").read_text(encoding="utf-8")

        self.assertIn("# Lolita Feed OS", readme)
        self.assertNotIn("# Lolita Radar OS", readme)
        self.assertIn("run-loop \\", readme)
        self.assertIn("--log-file .data/soak/lolita-radar-os-24h.log", readme)
        self.assertIn("--exit-file .data/soak/lolita-radar-os-24h.exit", readme)
        self.assertIn("--expected-cycles 288", readme)
        self.assertIn("verify-loop \\", readme)
        self.assertIn("cycle | checked_at | ok | event_count | error_message", readme)
        self.assertIn("source runs must fall inside that same window", readme)
        self.assertIn("Duplicate cycle", readme)
        self.assertIn("partially missing cycle `checked_at` values", readme)
        self.assertIn("values outside the evidence window are rejected", readme)
        self.assertIn("duplicate_cycles", readme)
        self.assertIn("missing_cycle_timestamps", readme)
        self.assertIn("cycle_time_mismatches", readme)
        self.assertIn("pull_request", readme)
        self.assertIn("Feed OS audit JSON", readme)
        self.assertIn("collector/   server-side collectors", readme)
        self.assertIn("python -m lolita_radar.cli seed-collectors", readme)
        self.assertIn("python -m lolita_radar.cli collect", readme)
        self.assertIn("python -m lolita_radar.cli run-once", readme)
        self.assertIn("--include-collectors", readme)
        self.assertIn("collect --baseline-only", readme)
        self.assertIn("collector_jobs", readme)
        self.assertIn("shop_items", readme)
        self.assertIn("market_samples", readme)
        self.assertIn("Open shop manually", readme)
        self.assertIn("Alert Feed: system-level market and source-health warnings", readme)
        self.assertNotIn("Alert Feed: new releases", readme)
        self.assertIn("GET /api/feed", readme)
        self.assertIn("GET /api/state", readme)
        self.assertIn("same public Feed OS payload", readme)
        self.assertIn("Internal state blocks", readme)
        self.assertIn("opportunity_radar", readme)
        self.assertIn("not exposed by", readme)
        self.assertIn("page_level", readme)
        self.assertIn("without becoming Drop Feed item cards", readme)
        self.assertIn("Drop Feed: first-seen public `shop_events`", readme)
        self.assertIn("Trend Feed: rule-based asking price trend", readme)
        self.assertIn("linked item hashes scoped to the item link and parent item context", readme)
        self.assertIn("First-seen item URL/title hash creates a `DROP` event", readme)
        self.assertIn("Price changes create `PRICE_CHANGED`", readme)
        self.assertIn("Availability changes create `STOCK_CHANGED`", readme)
        self.assertIn("Taobao and Goofish/Xianyu are intentionally placeholders", readme)
        self.assertIn("Legacy `generic_page` DROP", readme)
        self.assertIn("Explicit `content_changed` rows are kept out of Drop", readme)
        self.assertIn("copy edits and outer-page noise do not masquerade as new items", readme)
        self.assertIn("Console notifications render local Feed OS card-style summaries", readme)
        self.assertNotIn("Drop Feed: public proxy-shop or Taobao-style page changes", readme)
        self.assertNotIn("either a new item event or one of the configured", readme)


if __name__ == "__main__":
    unittest.main()
